name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Deploy to EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ec2-user
          EC2_KEY: ${{ secrets.EC2_KEY }}
        run: |
          echo "$EC2_KEY" > private_key.pem
          chmod 400 private_key.pem
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${EC2_USER}@${EC2_HOST} << 'EOF'
            # Navigate to app directory (create if not exists)
            mkdir -p ~/myapp
            cd ~/myapp
            # Pull latest code
            git pull origin main || git clone https://github.com/yourusername/myapp.git .
            # Install dependencies
            npm install
            # Restart app with PM2
            pm2 restart src/index.js || pm2 start src/index.js
          EOF